### ISSUE TITLE
 Connection problem

### ISSUE THREAD

**Issue by Tierrox** [petercunha/Knock#5]
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: connect ECONNREFUSED 127.0.0.1:6379
(node:4905) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: connect ECONNREFUSED 127.0.0.1:6379

**Comment by petercunha** [comment]
Make sure you have Redis running on port 6379!
